webhook-project/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "pages#dashboard"

  get "dashboard", to: "pages#dashboard"
  resources :webhooks, only: %i[new create destroy] do
    get "status_check", as: "status_check"
  end
end

webhook-project/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

webhook-project/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :webhook
end

webhook-project/app/models/webhook.rb
class Webhook < ApplicationRecord
  validates_format_of :url, with: /(http|https).+/i
  belongs_to :user

  enum status: {
    "unknown": 0,
    "checking": 1,
    "active": 2,
    "failed": 3,
  }
end

webhook-project/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

webhook-project/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!

  def dashboard
  end
end

webhook-project/app/controllers/webhooks_controller.rb
class WebhooksController < ApplicationController
  before_action :authenticate_user!

  def new
    render locals: {
      webhook: Webhook.new(user: current_user)
    }
  end

  def create
    webhook = Webhook.new(webhook_params)
    if webhook.save
      redirect_to dashboard_path
    else
      render "new", locals: {
        webhook: webhook,
      }
    end
  end

  def destroy
    webhook.destroy
    redirect_to dashboard_path

  end

  def status_check
    BackgroundJob::Webhook::StatusCheck.perform_async(webhook.id)
    redirect_to dashboard_path
  end

  private

  def webhook_params
    params.require(:webhook).permit(:user_id, :url)
  end

  def webhook
    Webhook.find_by(params.permit(:id, :webhook_id).transform_keys { |k| k == "webhook_id" ? "id" : k })
  end
end

webhook-project/app/helpers/application_helper.rb
module ApplicationHelper
end

webhook-project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebhookProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

webhook-project/app/views/pages/dashboard.html.erb
<div class="card w-50 mx-auto my-4">
  <div class="card-header text-center">
    Webhooks
  </div>
  <div class="card-body text-center">
    <%= turbo_frame_tag "webhook_frame" do %>
      <% if current_user.webhook.present? %>
          <%= render current_user.webhook %>
      <% else %>
          <%= link_to "Add Webhook", new_webhook_path, class: "btn btn-primary" %>
      <% end %>
    <% end %>
  </div>
</div>

webhook-project/app/views/webhooks/_webhook.html.erb
<%= turbo_stream_from webhook %>
<div id="<%= dom_id(webhook) %>">
  You have a webhook setup <%= webhook.url %>
  <br>
  Current Status: <%= webhook.status.capitalize %>
  <br>
  <%= link_to "Check Connectivity", webhook_status_check_path(webhook), class: "btn btn-warning m-4" %>
  <%= button_to "Remove", webhook_path(webhook), method: :delete, class: "btn btn-danger" %>
</div>

webhook-project/app/views/webhooks/new.html.erb
<%= turbo_frame_tag "webhook_frame" do %>
  <%= simple_form_for webhook do |f| %>
    <%= f.input :user_id, as: :hidden %>
    <%= f.input :url, as: :string %>
    <%= f.button :submit, class: "btn btn-primary m-4" %>
  <% end %>
  <%= link_to "Cancel", dashboard_path, class: "btn btn-danger" %>
<% end %>